### ISSUE TITLE
Multicheckbox UI

### ISSUE THREAD

**Issue by Karvan** [Geeksltd/Olive#159]
Each time you pick an Item in multi checkbox dropdown control, drop down collapses and you need to open again. 

it needs to keep open while the user hasn't clicked on the other areas.

**Comment by iPazooki** [comment]
Hi @Karvan 
Sorry for late reply, I tried to re-open the dropdown after each postback, but I was not able since we refresh the main tag of the page using ajax and keeping the state of each HTML control is not possible.

I think the only way to handle this situation is to prevent M# from generating `onChange` event and you handle this situation on the UI side using your own jQuery code.

**Comment by Karvan** [comment]
Hi @iPazooki 

I see, but while the Old Msharp had this feature could you please confirm with @PaymonK that we need to handle that in each project which we need.

**Comment by iPazooki** [comment]
@Karvan 
you are right, former Msharp generated completely different style, I mean it was completely something else, I will talk with Paymon

**Comment by HamidTheGeek** [comment]
It's sorted [here](https://github.com/Geeksltd/Olive.MvcJs/issues/126)
