### ISSUE TITLE
SecurityChecks() Method

### ISSUE THREAD

**Issue by mania-afshar** [Geeksltd/Olive#70]
In our modules we have set the SecurityChecks method based on users' roles so that each page is only accessible to certain roles, for example SecurityChecks(@"User.IsInRole(""Admin"")"); I would then expect that if a user without the correct permission copies and pastes the URL directly into the browser's address bar, they should receive an unauthorised result and be prevented from seeing the page. This is not happening at the moment. 

As a workaround, we also tried the VisibleIf() method with the same criteria. Although this sets the value for info.IsVisible correctly, all users are still able to see the content of the page.

**Comment by iPazooki** [comment]
@mania-afshar  Thanks for reporting. I have checked this issue and you are right about this, it seems because there is no `await next();` after generated `context.Result = Unauthorized();`. incidentally, you should inform @PaymonK  about this issue. it's related to the **M#**.

related [help link](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1).

**Comment by iPazooki** [comment]
@PaymonK  For example, in the MindMap project, add `SecurityChecks(@"User.IsInRole(""Sample1"")");` to the `NodeForm.cs` in the **#UI** project.

**Comment by mania-afshar** [comment]
This issue has been fixed with the latest updates. Thanks.

**Comment by iPazooki** [comment]
@PaymonK please close this issue.
